package ca.uwo.wts.owl.data.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AssignmentAssignment was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AssignmentAssignment extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ASSIGNMENT_ID_PK_COLUMN = "ASSIGNMENT_ID";

    public static final Property<String> ASSIGNMENT_ID = Property.create("assignmentId", String.class);
    public static final Property<String> CONTEXT = Property.create("context", String.class);
    public static final Property<String> XML = Property.create("xml", String.class);

    protected String assignmentId;
    protected String context;
    protected String xml;


    public String getAssignmentId() {
        beforePropertyRead("assignmentId");
        return this.assignmentId;
    }

    public String getContext() {
        beforePropertyRead("context");
        return this.context;
    }

    public String getXml() {
        beforePropertyRead("xml");
        return this.xml;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "assignmentId":
                return this.assignmentId;
            case "context":
                return this.context;
            case "xml":
                return this.xml;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "assignmentId":
                this.assignmentId = (String)val;
                break;
            case "context":
                this.context = (String)val;
                break;
            case "xml":
                this.xml = (String)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.assignmentId);
        out.writeObject(this.context);
        out.writeObject(this.xml);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.assignmentId = (String)in.readObject();
        this.context = (String)in.readObject();
        this.xml = (String)in.readObject();
    }

}
