package ca.uwo.wts.owl.data.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AssignmentSubmission was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AssignmentSubmission extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String SUBMISSION_ID_PK_COLUMN = "SUBMISSION_ID";

    public static final Property<String> SUBMISSION_ID = Property.create("submissionId", String.class);
    public static final Property<String> CONTEXT = Property.create("context", String.class);
    public static final Property<String> SUBMITTER_ID = Property.create("submitterId", String.class);
    public static final Property<String> SUBMIT_TIME = Property.create("submitTime", String.class);
    public static final Property<String> SUBMITTED = Property.create("submitted", String.class);
    public static final Property<String> GRADED = Property.create("graded", String.class);
    public static final Property<String> XML = Property.create("xml", String.class);

    protected String submissionId;
    protected String context;
    protected String submitterId;
    protected String submitTime;
    protected String submitted;
    protected String graded;
    protected String xml;


    public String getSubmissionId() {
        beforePropertyRead("submissionId");
        return this.submissionId;
    }

    public String getContext() {
        beforePropertyRead("context");
        return this.context;
    }

    public String getSubmitterId() {
        beforePropertyRead("submitterId");
        return this.submitterId;
    }

    public String getSubmitTime() {
        beforePropertyRead("submitTime");
        return this.submitTime;
    }

    public String getSubmitted() {
        beforePropertyRead("submitted");
        return this.submitted;
    }

    public String getGraded() {
        beforePropertyRead("graded");
        return this.graded;
    }

    public String getXml() {
        beforePropertyRead("xml");
        return this.xml;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "submissionId":
                return this.submissionId;
            case "context":
                return this.context;
            case "submitterId":
                return this.submitterId;
            case "submitTime":
                return this.submitTime;
            case "submitted":
                return this.submitted;
            case "graded":
                return this.graded;
            case "xml":
                return this.xml;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "submissionId":
                this.submissionId = (String)val;
                break;
            case "context":
                this.context = (String)val;
                break;
            case "submitterId":
                this.submitterId = (String)val;
                break;
            case "submitTime":
                this.submitTime = (String)val;
                break;
            case "submitted":
                this.submitted = (String)val;
                break;
            case "graded":
                this.graded = (String)val;
                break;
            case "xml":
                this.xml = (String)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.submissionId);
        out.writeObject(this.context);
        out.writeObject(this.submitterId);
        out.writeObject(this.submitTime);
        out.writeObject(this.submitted);
        out.writeObject(this.graded);
        out.writeObject(this.xml);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.submissionId = (String)in.readObject();
        this.context = (String)in.readObject();
        this.submitterId = (String)in.readObject();
        this.submitTime = (String)in.readObject();
        this.submitted = (String)in.readObject();
        this.graded = (String)in.readObject();
        this.xml = (String)in.readObject();
    }

}
