package ca.uwo.wts.owl.data.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import ca.uwo.wts.owl.data.SakaiRealm;
import ca.uwo.wts.owl.data.SakaiRealmFunction;
import ca.uwo.wts.owl.data.SakaiRealmRole;

/**
 * Class _SakaiRealmRlFn was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SakaiRealmRlFn extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String FUNCTION_KEY_PK_COLUMN = "FUNCTION_KEY";
    public static final String REALM_KEY_PK_COLUMN = "REALM_KEY";
    public static final String ROLE_KEY_PK_COLUMN = "ROLE_KEY";

    public static final Property<Long> REALM_KEY = Property.create("realmKey", Long.class);
    public static final Property<Long> FUNCTION_KEY = Property.create("functionKey", Long.class);
    public static final Property<Long> ROLE_KEY = Property.create("roleKey", Long.class);
    public static final Property<SakaiRealmRole> SAKAI_REALM_ROLE = Property.create("sakaiRealmRole", SakaiRealmRole.class);
    public static final Property<SakaiRealm> SAKAI_REALM = Property.create("sakaiRealm", SakaiRealm.class);
    public static final Property<SakaiRealmFunction> SAKAI_REALM_FUNCTION = Property.create("sakaiRealmFunction", SakaiRealmFunction.class);

    protected Long realmKey;
    protected Long functionKey;
    protected Long roleKey;

    protected Object sakaiRealmRole;
    protected Object sakaiRealm;
    protected Object sakaiRealmFunction;

    public void setRealmKey(Long realmKey) {
        beforePropertyWrite("realmKey", this.realmKey, realmKey);
        this.realmKey = realmKey;
    }

    public Long getRealmKey() {
        beforePropertyRead("realmKey");
        return this.realmKey;
    }

    public void setFunctionKey(Long functionKey) {
        beforePropertyWrite("functionKey", this.functionKey, functionKey);
        this.functionKey = functionKey;
    }

    public Long getFunctionKey() {
        beforePropertyRead("functionKey");
        return this.functionKey;
    }

    public void setRoleKey(Long roleKey) {
        beforePropertyWrite("roleKey", this.roleKey, roleKey);
        this.roleKey = roleKey;
    }

    public Long getRoleKey() {
        beforePropertyRead("roleKey");
        return this.roleKey;
    }

    public void setSakaiRealmRole(SakaiRealmRole sakaiRealmRole) {
        setToOneTarget("sakaiRealmRole", sakaiRealmRole, true);
    }

    public SakaiRealmRole getSakaiRealmRole() {
        return (SakaiRealmRole)readProperty("sakaiRealmRole");
    }

    public void setSakaiRealm(SakaiRealm sakaiRealm) {
        setToOneTarget("sakaiRealm", sakaiRealm, true);
    }

    public SakaiRealm getSakaiRealm() {
        return (SakaiRealm)readProperty("sakaiRealm");
    }

    public void setSakaiRealmFunction(SakaiRealmFunction sakaiRealmFunction) {
        setToOneTarget("sakaiRealmFunction", sakaiRealmFunction, true);
    }

    public SakaiRealmFunction getSakaiRealmFunction() {
        return (SakaiRealmFunction)readProperty("sakaiRealmFunction");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "realmKey":
                return this.realmKey;
            case "functionKey":
                return this.functionKey;
            case "roleKey":
                return this.roleKey;
            case "sakaiRealmRole":
                return this.sakaiRealmRole;
            case "sakaiRealm":
                return this.sakaiRealm;
            case "sakaiRealmFunction":
                return this.sakaiRealmFunction;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "realmKey":
                this.realmKey = (Long)val;
                break;
            case "functionKey":
                this.functionKey = (Long)val;
                break;
            case "roleKey":
                this.roleKey = (Long)val;
                break;
            case "sakaiRealmRole":
                this.sakaiRealmRole = val;
                break;
            case "sakaiRealm":
                this.sakaiRealm = val;
                break;
            case "sakaiRealmFunction":
                this.sakaiRealmFunction = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.realmKey);
        out.writeObject(this.functionKey);
        out.writeObject(this.roleKey);
        out.writeObject(this.sakaiRealmRole);
        out.writeObject(this.sakaiRealm);
        out.writeObject(this.sakaiRealmFunction);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.realmKey = (Long)in.readObject();
        this.functionKey = (Long)in.readObject();
        this.roleKey = (Long)in.readObject();
        this.sakaiRealmRole = in.readObject();
        this.sakaiRealm = in.readObject();
        this.sakaiRealmFunction = in.readObject();
    }

}
